# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    # Enable the atomic codegen option for Xtensa
    "-C",
    "target-feature=+s32c1i",

    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Wl,-Tlinkall.x",
]

[build]
target = "xtensa-esp32s2-none-elf"

[unstable]
build-std = ["core", "alloc"]
